### PR TITLE
Use "strlen" to determine the length of char-array "values"

### PR DESCRIPTION
**Pull request by BenzinoNapoloni**
See my comment in issue https://github.com/eduardok/libsmbclient-php/issues/98

### CODE REVIEW

**Comment by eduardok** [comment]
Please review the latest release, 1.0.7, and resubmit if needed.

**Comment by SkyBeam** [comment]
I did get version 1.1.0 on my gentoo box. Unfortunately nextcloud still failing to access smb storages. So I am back at patched version described here: https://github.com/nextcloud/server/issues/36773

**Comment by remicollet** [comment]
Indeed, I notice a change in recent libsmbclient 
See https://bugzilla.samba.org/show_bug.cgi?id=14808 and https://github.com/samba-team/samba/commit/113536e0d735a5235f8be29d4fd1cfc8177930b1

So with version < 4.16 `smbc_getxattr` returns the length on success (>= 0 for success, <0 for error)
Since 4.16 it returns 0 on success

**Comment by remicollet** [comment]
I need a way to reproduce without a Windows computer... :s

**Comment by SkyBeam** [comment]
Why do you think you need Windows? For the use-case referred here you need Samba 4.17.5 or newer and a NextCloud server to configure an external storage pointing to a Samba share.

**Comment by remicollet** [comment]
@SkyBeam yes, I was able to reproduce and this to propose #100

**Pull request closed without merging**
