### PR TITLE
provide test suite in archive

### PR DESCRIPTION
**Pull request by remicollet**
Just a terrible bad practice to exclude test suite from archive.

### CODE REVIEW

**Comment by aklomp** [comment]
I disagree. The tests were deliberately removed from the release tarballs in 5f3fc5e, because I believe they do not belong in a release tarball. In my opinion, a release tarball should contain only the minimal, final, shipping code. (It should also ship with the autotools stuff pre-generated, etc.) Tests are useful only for developers/testers, and even more so when the test environment is tricky to replicate. The tests can be accessed by cloning the project (getting the "dev version"), but release tarballs are for end users.

**Comment by bochecha** [comment]
How do end users verify that the code in the release tarball works, if it doesn't include the unit tests?

In fact, how do **you** verify that the code in the release tarball works, if it doesn't include the unit tests?

**Comment by aklomp** [comment]
End users don't verify the code in the tarball. They have no need to, they're end users. If they want to wear the developer hat, they can clone the full project and get the dev history, tests, .gitignore, and so on.

I don't understand the second question. All release code has been tested against the test suite, obviously. That the release tarball does not include the test suite does not change that.

**Comment by bochecha** [comment]
> I don't understand the second question. All release code has been tested against the test suite, obviously.

It has been tested in the git tree, yes.

What you seem to be saying is that the tarballs **themselves** aren't tested at all then, which is worrying.

There are many cases where the tests could succeed in the git tree, but fail in a release tarballs.

For example, a file could be present in the git tree but missing from the tarball (if it hasn't been added to `EXTRA_DIST` with the autotools for `make distcheck`-generated tarballs, or if `git archive` has a bug, or ...)

Another example is that the test suite makes assumptions about being run inside a git tree (libgit2 does that for one of its unit tests which uses the libgit2 git tree itself as a test repo).

We could go on with other ways to have busted tarballs even though the test suite passed just fine inside the git tree.

The point is, you are distributing your code in 2 forms: the git tree and release tarballs. Both should be tested.

(side note)
I'd personally prefer that we (the FOSS community) collectively decide on giving up tarballs entirely, and have everything (users, RPMs, etc...) use signed release tags directly from the SCM, but that's not (yet?) the world we live in.

And in the meantime, if an upstream is providing release tarballs at all, they should be tested.
(end of the side note)

In fact, that's exactly what things like `make distcheck` do: they will generate a tarball, then extract it and run `make check` inside. It is a very good practice that really needs to be a core part of releasing tarballs. (as long as you're providing tarballs, that is :wink:)

**Comment by bochecha** [comment]
> End users don't verify the code in the tarball. They have no need to, they're end users.

One of the very important properties of Free Software is that end users can verify the software they run. (if they want to)

This is the whole point of the Debian "reproducible builds" initiative, for example.

Having tests part of the release tarballs is also a necessary (but not sufficient) condition to allow end users to verify the code that they run.

**Comment by eduardok** [comment]
Well, basically 2 different points of view, both reasonable to me. However, if Alfred doesn't have a compelling negative reason to keep them out, we should take the inclusive approach and have them back. This is the logic I would use to settle on point-of-view issues (inclusiveness).
What do you guys think?

**Comment by aklomp** [comment]
> What you seem to be saying is that the tarballs themselves aren't tested at all then, which is worrying.

Right, they are not tested. I don't think it's possible to hook Travis up to test a release tarball, regardless of whether it contains tests or not. That would leave a manual process, and we don't have such in place right now. I disagree that that is cause for worry. The code itself is what we should, and do, test, at a functional level. The release tarball is just a view of the tested code without the tests. Since the code does not depend on the tests (which would be a bug, but not one that could be found through the test suite), there is no functional difference to test.

Should the tarballed code fail to compile or install as intended, which I think your concern is, then that is obviously a bug. But it has nothing to do with the *functional* tests on the code passing or not -- it would be a *packaging* bug. Compiling and installing are not tested by the test suite anyway.

> One of the very important properties of Free Software is that end users can verify the software they run. (if they want to)

Everybody is free to clone the project and checkout the latest release tag. They will get the full dev environment which contains the git history, the tests and so on. Nothing is being withheld at all from the end user who wants to verify.

> Well, basically 2 different points of view, both reasonable to me. However, if Alfred doesn't have a compelling negative reason to keep them out, we should take the inclusive approach and have them back. This is the logic I would use to settle on point-of-view issues (inclusiveness).

I don't have a compelling negative reason to leave out the tests, other than personal taste and doubts about how easy it is to set up the test environment. But if I'm the minority, I will accept that I may be wrong, and pull this request.

**Comment by remicollet** [comment]
Despite it seems to be a common (and very bad) practice to not provide test suite for pure-PHP libraries (which is IMHO only a composer issue), this is not a pure-PHP library.

A "C" projects provide their test suite, which include PHP itself, and all PHP extension (from PECL forge or other).

In all case, even can do its best  to ensure it works on the dev system, and on travis (Debian, AFAIK), but no way to test user system (different system, PHP version, compiler, libraries...)

Even, why do you think "make" display:

    Build complete.
    Don't forget to run 'make test'.

And, yes, most of real "end-users" will not run the test suite, but they will also prefer to not build from sources (and use distribution well tested binary packages)

**Comment by remicollet** [comment]
Thanks

**Pull request merged**
