### PR TITLE
Allow to override test suite configuration

### PR DESCRIPTION
**Pull request by remicollet**
This seems more flexible for people wanting to test

### CODE REVIEW

**Comment by aklomp** [comment]
Hi Remi, just for your information, I will change the license of this repo to the BSD 2-clause license later today (see issue #15). So if we pull this request, it will fall under the new license. Is that okay with you?

**Comment by remicollet** [comment]
@aklomp yes BSD is fine for me (even if PHP License is fine, ok not perfect for non PHP project, but debian is wrong on this ;)

**Comment by remicollet** [comment]
I definitively don't understand why travis fails... it works locally.

    $ php -d extension=modules/libsmbclient.so /usr/local/bin/phpunit.phar -c tests/phpunit.xml -v
    PHPUnit 4.8.6 by Sebastian Bergmann and contributors.
    Runtime:	PHP 5.6.12
    Configuration:	/work/GIT/libsmbclient-php/tests/phpunit.xml
    .............................................
    Time: 366 ms, Memory: 15,75Mb
    OK (45 tests, 145 assertions)

**Comment by aklomp** [comment]
This pull request looks sensible. I'm willing to merge it, as long as the Travis build passes and if you squash some of the fixup commits :)

**Comment by aklomp** [comment]
With the Travis error, it looks like one or both of the SMB_ constants is empty. It's strange because the code looks fine...

**Comment by aklomp** [comment]
Maybe try replacing the concatenation in `LSeekTest.php` with

```php
sprintf("smb://%s/%s/lseektest.txt", SMB_HOST, SMB_SHARE);
```

**Comment by remicollet** [comment]
Got it \o/

**Comment by aklomp** [comment]
Woah :)  OK, I'll look into this pull request late this evening. Could you please quash your commits into a nice and small patchset?

**Pull request closed without merging**
