### PR TITLE
initial 'smb' streams support

### PR DESCRIPTION
**Pull request by remicollet**
Please don't merge this, initial work in progress
Open for discussion.

Most changes in sources are factorization (to avoid copy/paste in streams wrapper)

### CODE REVIEW

**Comment by remicollet** [comment]
Start to be usable, any comment on this feature ?

**Comment by aklomp** [comment]
Excellent work! Looks solid to me. If I had more experience with PHP internals I could give better feedback. Here are some first thoughts:

- The new code uses `php_error_docref()`, not `php_error()`, for printing errors. Is one superior to the other, and should we switch in the whole codebase?
- The stream feature needs documentation in the README.
- When you're satisfied, please squash your commits so that history is linear (no changes by previous commits are overwritten by later commits).

**Comment by remicollet** [comment]
> The new code uses php_error_docref(), not php_error(), for printing errors. Is one superior to the other, and should we switch in the whole codebase?

Mostly eq., IIRC excepted in TS mode where a TSRMLS_FETCH is saved.

**Comment by remicollet** [comment]
> When you're satisfied, please squash your commits so that history is linear (no changes by previous commits are overwritten by later commits).

I don't know how to do this simply, except by closing this PR and open a new one with a single commit... :(

**Comment by aklomp** [comment]
Just force-push over your `issue-stream` branch. GitHub will update the pull request automatically.

**Comment by remicollet** [comment]
I think all possible features are now implemented (latest, chmod, touch, are 5.4+ only).

**Comment by remicollet** [comment]
On my side, everything is done.

Ready for review / merge.

Notice, I have change version to 0.8.0-dev.
If merged, probably worth to set to 0.8.0beta and tag a pre-release version, to get user feedback.

**Comment by aklomp** [comment]
Hi Remi, thanks for the excellent, high quality work. You even copied the project's coding style, nice. I think this can be merged without further discussion. At the most I think the README could use a code example of this new functionality. But we can always add one later. Eduardo?

**Comment by remicollet** [comment]
> At the most I think the README could use a code example of this new functionality.

Isn't  01e2401 enough ?
But yes other can be added later.

Perhaps, could recommend to use the functions instead streams for massive action (single context, instead of new context for each command)

**Comment by aklomp** [comment]
With the examples thing I meant put full code samples in the Examples section. But maybe the current example is enough for demonstration, since the streams API is more for one-shot use anyway. We can always add examples later.

Your contribution looks excellent, but I have a few questions/comments, which I will add as annotations.

**Comment by remicollet** [comment]
The "cleanups" commit should take care of all comments.

**Comment by aklomp** [comment]
Merged, and thank you for the great contribution!

**Pull request merged**
