### PR TITLE
PHP 7 compatibility

### PR DESCRIPTION
**Pull request by remicollet**
Another important PR / feature ;)

Should be "noop" for PHP 5

### CODE REVIEW

**Comment by remicollet** [comment]
Of course: 

     $ php -d extension=modules/libsmbclient.so /usr/bin/phpunit tests -v
     PHPUnit 4.8.6 by Sebastian Bergmann and contributors.
     
     Runtime:	PHP 7.0.0RC2
     Configuration:	/work/GIT/libsmbclient-php/phpunit.xml

     ............................................................
     
     Time: 545 ms, Memory: 6.00Mb
     
     OK (60 tests, 206 assertions)

**Comment by aklomp** [comment]
It would be cool to test this with Travis, which [is getting some support for PHP7](http://docs.travis-ci.com/user/languages/php/#PHP-7).

**Comment by remicollet** [comment]
Yes we need to tweak the travis config to run test against 5.3, 5.4, 5.5, 5.6 and master
Could be done in a separate thread (don't want to pollute this PR)

**Comment by aklomp** [comment]
Merged, thanks!

**Comment by aklomp** [comment]
The difficult thing about updating the Travis config is that we now categorize libsmbclient-php as a C project which incidentally runs some PHP. That gives us our C build environment for free, but limits us to one version of PHP (the one we download and build against).

To test properly under different versions of PHP, we would have to recategorize this project as a PHP project that incidentally compiles some C. But I think even then it's hard, because I don't know if you get all the matching development headers per version of PHP. And we'd have to set up a C environment in each machine instance.

**Comment by remicollet** [comment]
For travis, you can look at https://github.com/remicollet/pecl-json-c 
( integration done by @m6w6 )

**Comment by m6w6** [comment]
I guess I could create a PR for https://github.com/m6w6/travis-pecl, if wanted.

**Pull request merged**
